Do not use setup-python for Conan installation (#5)
* Use system python to install Conan

Signed-off-by: Uilian Ries <uilianries@gmail.com>

* Split check conan version

Signed-off-by: Uilian Ries <uilianries@gmail.com>

* Show Python version

Signed-off-by: Uilian Ries <uilianries@gmail.com>

* Document about pkg_config_path

Signed-off-by: Uilian Ries <uilianries@gmail.com>

* Simplify README.md

Co-authored-by: Carlos Zoido <mrgalleta@gmail.com>

* Add deprecation message for python_version

Signed-off-by: Uilian Ries <uilianries@gmail.com>

* Document deprecated option

Signed-off-by: Uilian Ries <uilianries@gmail.com>

* Respect grammar

Signed-off-by: Uilian Ries <uilianries@gmail.com>

* Emphatize python-setup section

Signed-off-by: Uilian Ries <uilianries@gmail.com>

* Revert python_version description

Co-authored-by: Carlos Zoido <mrgalleta@gmail.com>

---------

Signed-off-by: Uilian Ries <uilianries@gmail.com>
Co-authored-by: Carlos Zoido <mrgalleta@gmail.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -27,6 +27,7 @@ inputs:
     description: 'Python version to install'
     required: false
     default: '3.10'
+    deprecationMessage: 'This input is deprecated and will be removed in future versions. Use the Python version set in the GitHub runner instead or a GitHub Action to set up Python.'
 
 outputs:
   conan-version:
@@ -39,17 +40,17 @@ outputs:
 runs:
   using: 'composite'
   steps:
-    - name: 'Install Python'
-      uses: actions/setup-python@v5
-      id: setup-python
-      with:
-        python-version: ${{ inputs.python_version }}
-
-    - name: 'Get installed Python version'
-      id: get-python-version
+    - name: Check Conan version
       shell: bash
+      id: check-conan-version
       run: |
-        echo "python-version=$(python --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT
+        if [ -n "${{ inputs.version }}" ]; then
+          conan_version="${{ inputs.version }}"
+          if [[ "$conan_version" == 1.* ]]; then
+            echo "ERROR: Conan 1.x is not supported. Please use Conan 2.x"
+            exit 1
+          fi
+        fi
 
     - name: Set CONAN_HOME
       if: ${{ inputs.home != '' }}
@@ -62,15 +63,14 @@ runs:
       shell: bash
       id: install-conan
       run: |
+        python --version
+        python -m pip install --upgrade pip
+        python -m pip --version
         if [ -n "${{ inputs.version }}" ]; then
           conan_version="${{ inputs.version }}"
-          if [[ "$conan_version" == 1.* ]]; then
-            echo "ERROR: Conan 1.x is not supported. Please use Conan 2.x"
-            exit 1
-          fi
-          pip install conan==${{ inputs.version }}
+          python -m pip install conan==${{ inputs.version }}
         else
-          pip install conan
+          python -m pip install conan
         fi
         echo "conan-version=$(conan --version | cut -d' ' -f3)" >> $GITHUB_OUTPUT
 
